services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
